version: "3.5"
services:
    tnmap-api:
        env_file: .env
        build:
            context: .
            dockerfile: ${DOCKERFILE}
        volumes:
            - .:/app
        restart: always
        ports:
            - '8000:8000'
        networks:
            - mysql-network
            - api-network
networks:
    mysql-network:
        name: mysql-network
        external: true
    api-network:
        name: api-network
        driver: bridge
